### ISSUE TITLE
ws.audioscrobbler.com has no proper SSL support

### ISSUE THREAD

**Issue by dmalikov** [supki/liblastfm#27]
https://www.ssllabs.com/ssltest/analyze.html?d=ws.audioscrobbler.com

Currently, ws.audioscrobbler.com uses RC4-MD5 as a cipher suite, which makes `ht-tls` library unable to do a proper handshake.

Thus, almost every liblastfm function fails with one of the following errors:

```
LastfmHttpError (TlsExceptionHostPort (HandshakeFailed (Error_Protocol ("expecting server hello, got alert : [(AlertLevel_Fatal,DecodeError)]",True,HandshakeFailure))) "ws.audioscrobbler.com" 443)
LastfmHttpError (FailedConnectionException2 "ws.audioscrobbler.com" 443 True <socket: 13>: hPutBuf: resource vanished (Broken pipe))
```

**Comment by supki** [comment]
Apparently, they fixed the problem: https://www.ssllabs.com/ssltest/analyze.html?d=ws.audioscrobbler.com

**Comment by dmalikov** [comment]
I'd propose to switch back then and drop this `https` function

**Comment by supki** [comment]
Seems reasonable.
